license = "MIT OR Apache-2.0"

[workspace]
members = [
    "examples/examples01", "examples/examples02",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bevy = "0.15.1"
